property_id: "1118802694993580977"
property_bedrooms: 1
property_name: "Lit Spot"      
property_description: "Prime location for your awesome vacation or productive work trip. With excellent public transport connections and Sofia's top attractions just around the corner, you'll have the best of the city right at your doorstep. Wander through historic sites, indulge in local cuisine, or just soak up the vibrant city vibe. Relax in our cozy living space, complete with all the essentials for a stress-free stay - WiFi, workspace, washing machine, cleaning supplies, and a small hub for quick meals.
  The space
  Top-Notch Location:
  - Heart of Sofia with unbeatable public transport connections.
  - Located just opposite the Sofia University, 200 meters away from a metro station, and only a 5-minute walk from the Alexander Nevsky Cathedral.
  - Sofia’s top attractions, vibrant neighborhoods, and business districts just around the corner.
  - Situated in a quiet residential building in one of the most emblematic and charming areas in the center of the city.
  
  Explore and Enjoy:
  - Dive into history with landmarks like Alexander Nevsky Cathedral and Serdica ruins.
  - Wander Vitosha Boulevard for shopping, dining, and trendy cafes.
  - Experience Sofia’s nightlife and cultural hotspots.
  
  Cozy Living Space:
  - Large common space with a comfortable double bed.
  - Perfect for unwinding after a busy day.
  - High-speed WiFi for seamless streaming and staying connected.
  
  Productivity Ready:
  - Dedicated workspace for a quiet and comfortable working environment.
  - Ideal for remote work or catching up on projects.
  
  Home Comforts:
  - Washing machine and cleaning supplies provided.
  - Iron, ironing table, and clothing storage options available.
  - Drying rack to keep your wardrobe fresh and organized.
  - Fresh bed sheets, spare sets, and towels for your convenience.
  - Bathroom with a shower and sink, plus a separate small toilet.
  
  Kitchen Essentials:
  - Compact yet functional hub with essential kitchen appliances.
  - Cooking equipment, dishes, and dining supplies for quick bites or full meals.
  - Brazil express 3 cup espresso coffee maker, electric Kettle.
  - Small fridge for groceries.
  - Hot water readily available for cooking and cleaning.
  
  Dining Area:
  - Cozy dining space with dishes, glasses, and everything you need for a pleasant meal.
  Guest access
  You will have secure access to all of the property, ensuring your stay is safe and private."
property_location: "Sofia, Sveti Kliment Ohridski street 6"
property_type: Studio
max_guests: 2
property_bathrooms: 1